mv BinnedReportTyphoid.cpp BinnedReportPyDemo.cpp
mv BinnedReportTyphoid.h BinnedReportPyDemo.h
mv IndividualTyphoid.cpp IndividualPyDemo.cpp
mv IndividualTyphoid.h IndividualPyDemo.h
mv InfectionTyphoid.cpp InfectionPyDemo.cpp
mv InfectionTyphoid.h InfectionPyDemo.h
mv NodeTyphoid.cpp NodePyDemo.cpp
mv NodeTyphoid.h NodePyDemo.h
mv ReportTyphoidByAgeAndGender.cpp ReportPyDemoByAgeAndGender.cpp
mv ReportTyphoidByAgeAndGender.h ReportPyDemoByAgeAndGender.h
mv ReportTyphoid.cpp ReportPyDemo.cpp
mv ReportTyphoid.h ReportPyDemo.h
mv SimulationTyphoid.cpp SimulationPyDemo.cpp
mv SimulationTyphoid.h SimulationPyDemo.h
mv SpatialReportTyphoid.cpp SpatialReportPyDemo.cpp
mv SpatialReportTyphoid.h SpatialReportPyDemo.h
mv SusceptibiliTyphoidTY.cpp SusceptibilityPyDemo.cpp
mv SusceptibiliTyphoidTY.h SusceptibilityPyDemo.h
mv TyphoidDefs.h PyDemoDefs.h
mv TyphoidDrugTypeParameters.cpp PyDemoDrugTypeParameters.cpp
mv TyphoidDrugTypeParameters.h PyDemoDrugTypeParameters.h
mv TyphoidInterventionsContainer.cpp PyDemoInterventionsContainer.cpp
mv TyphoidInterventionsContainer.h PyDemoInterventionsContainer.h
