
python .\extract_overrides.py defaults\hiv_scenario_default_config.json Scenarios\STIAndHIV\04_Health_Care\4_1_b_and_c_Property_Restriction\RestrictAtEventCoordinator\.config_from_excel.json > Scenarios\STIAndHIV\04_Health_Care\4_1_b_and_c_Property_Restriction\RestrictAtEventCoordinator\param_overrides.json 

python .\extract_overrides.py defaults\hiv_scenario_default_config.json Scenarios\STIAndHIV\04_Health_Care\4_1_b_and_c_Property_Restriction\RestrictAtNodeLevelHealthTriggeredIV\.config_from_excel.json > Scenarios\STIAndHIV\04_Health_Care\4_1_b_and_c_Property_Restriction\RestrictAtNodeLevelHealthTriggeredIV\param_overrides.json 


python .\extract_overrides.py defaults\hiv_scenario_default_config.json Scenarios\STIAndHIV\04_Health_Care\4_1_e_CascadeState_and_AbortState\.config_from_excel.json > Scenarios\STIAndHIV\04_Health_Care\4_1_e_CascadeState_and_AbortState\param_overrides.json 

python .\extract_overrides.py defaults\hiv_scenario_default_config.json Scenarios\STIAndHIV\04_Health_Care\4_2_2_c_ART_Eligibility\.config_from_excel.json > Scenarios\STIAndHIV\04_Health_Care\4_2_2_c_ART_Eligibility\param_overrides.json 

python .\extract_overrides.py defaults\hiv_scenario_default_config.json Scenarios\STIAndHIV\04_Health_Care\4_2_4_c_HIVMuxer\.config_from_excel.json > Scenarios\STIAndHIV\04_Health_Care\4_2_4_c_HIVMuxer\param_overrides.json 


python .\extract_overrides.py defaults\hiv_scenario_default_config.json Scenarios\STIAndHIV\04_Health_Care\4_3_Health_Care_Model_Baseline\.config_from_excel.json > Scenarios\STIAndHIV\04_Health_Care\4_3_Health_Care_Model_Baseline\param_overrides.json 

