

rem python y:\Scripts\json_to_xlsm.py Scenarios\STIAndHIV\04_Health_Care\4_1_b_and_c_Property_Restriction\RestrictAtEventCoordinatorical_Transmission\config.xlsm Scenarios\STIAndHIV\04_Health_Care\4_1_b_and_c_Property_Restriction\RestrictAtEventCoordinator
python y:\Scripts\json_to_xlsm.py Scenarios\STIAndHIV\03_Transmission\G_Vertical_Transmission\config.xlsm Scenarios\STIAndHIV\04_Health_Care\4_1_b_and_c_Property_Restriction\RestrictAtEventCoordinator
python y:\Scripts\json_to_xlsm.py Scenarios\STIAndHIV\03_Transmission\G_Vertical_Transmission\config.xlsm Scenarios\STIAndHIV\04_Health_Care\4_1_b_and_c_Property_Restriction\RestrictAtNodeLevelHealthTriggeredIV
python y:\Scripts\json_to_xlsm.py Scenarios\STIAndHIV\03_Transmission\G_Vertical_Transmission\config.xlsm Scenarios\STIAndHIV\04_Health_Care\4_1_e_CascadeState_and_AbortState
python y:\Scripts\json_to_xlsm.py Scenarios\STIAndHIV\03_Transmission\G_Vertical_Transmission\config.xlsm Scenarios\STIAndHIV\04_Health_Care\4_2_2_c_ART_Eligibility
python y:\Scripts\json_to_xlsm.py Scenarios\STIAndHIV\03_Transmission\G_Vertical_Transmission\config.xlsm Scenarios\STIAndHIV\04_Health_Care\4_2_4_c_HIVMuxer
python y:\Scripts\json_to_xlsm.py Scenarios\STIAndHIV\03_Transmission\G_Vertical_Transmission\config.xlsm Scenarios\STIAndHIV\04_Health_Care\4_3_Health_Care_Model_Baseline

